import { execSync } from 'child_process';
import { writeFileSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const gatewayRoot = path.resolve(__dirname, '..');
const outFile = path.join(gatewayRoot, 'src', 'version.generated.ts');

function tryGit(cmd: string): string | null {
  try {
    return execSync(cmd, { cwd: gatewayRoot, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return null;
  }
}

const pkgPath = path.join(gatewayRoot, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { version: string };

const devFallback = process.env.GATEWAY_VERSION_DEV === '1';
const gitSha = devFallback ? null : tryGit('git rev-parse HEAD');
const gitShort = devFallback ? null : tryGit('git rev-parse --short HEAD');
const status = devFallback ? null : tryGit('git status --porcelain');

const now = new Date().toISOString();
const GIT_SHA = gitSha ?? `dev-${Date.now()}`;
const GIT_SHORT = gitShort ?? GIT_SHA.substring(0, 7);
const DIRTY_FLAG = status != null && status.length > 0;

const content = `// AUTO-GENERATED by scripts/generate-version.ts. Do not edit.
export const VERSION_INFO = {
  GIT_SHA: ${JSON.stringify(GIT_SHA)},
  GIT_SHORT: ${JSON.stringify(GIT_SHORT)},
  BUILD_TIME: ${JSON.stringify(now)},
  PACKAGE_VERSION: ${JSON.stringify(pkg.version)},
  DIRTY_FLAG: ${DIRTY_FLAG},
} as const;
`;

writeFileSync(outFile, content);
console.log(`[generate-version] wrote ${path.relative(gatewayRoot, outFile)} (${GIT_SHORT}${DIRTY_FLAG ? '-dirty' : ''})`);
